# Generated by Django 4.2.11 on 2024-11-07 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_alergeni', models.CharField(choices=[('LACTOZA', 'lactoza'), ('GLUETEN', 'gluten'), ('NONE', 'none')], default='NONE')),
            ],
        ),
        migrations.CreateModel(
            name='Bauturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bautura', models.CharField(max_length=30)),
                ('temperatura', models.CharField(choices=[('RECE', 'rece'), ('CAMEREI', 'camerei'), ('CALDA', 'calda')], default='CAMEREI')),
            ],
        ),
        migrations.CreateModel(
            name='Biscuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_biscuite', models.CharField(choices=[('CIOCOLATA', 'ciocolata'), ('CIOCOLATA ALBA', 'ciocolata alba'), ('GRAHAM', 'graham'), ('DIGESTIVI', 'digestivi'), ('UNT', 'unt')], default='CIOCOLATA')),
            ],
        ),
        migrations.CreateModel(
            name='Informatii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specificatii', models.CharField(max_length=250)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('alergeni', models.ManyToManyField(to='Gelaterie.alergeni')),
            ],
        ),
        migrations.CreateModel(
            name='Inghetata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inghetata', models.CharField(choices=[('GELATO', 'gelato'), ('SORBET', 'sorbet')], default='GELATO')),
                ('aroma', models.CharField(choices=[('CIOCOLATA', 'ciocolata'), ('CIOCOLATA ALBA', 'ciocolata alba'), ('VANILIE', 'vanilie'), ('FISTIC', 'fistic'), ('COOKIES ADN CREAM', 'cookies and cream'), ('CARAMEL', 'caramel'), ('KINDER', 'kinder'), ('BUBBLEGUM', 'bubblegum'), ('ALUNE', 'alune'), ('CASTANE', 'castane'), ('PEPENE', 'pepene'), ('BANANA', 'banana'), ('CIRESE', 'cirese'), ('PIERSICI', 'piersici'), ('LAMAIE', 'lamaie')], default='CIOCOLATA')),
                ('mod_servire', models.CharField(choices=[('CON', 'con'), ('CUPA', 'cupa')], default='CON')),
                ('info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.informatii')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nume_magazin', models.CharField(max_length=50)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('orar', models.DateField(null=True)),
                ('email_magazin', models.EmailField(max_length=254, null=True)),
                ('numar_telefon_magazin', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_sponsor', models.CharField(max_length=100)),
                ('email_sponsor', models.EmailField(max_length=254, null=True)),
                ('numar_telefon_sponsor', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Torturi_Inghetata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_tort', models.CharField(max_length=40)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.informatii')),
                ('magazin', models.ManyToManyField(to='Gelaterie.magazine')),
            ],
        ),
        migrations.CreateModel(
            name='Prajituri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_prajitura', models.CharField(max_length=30)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.informatii')),
                ('magazin', models.ManyToManyField(to='Gelaterie.magazine')),
            ],
        ),
        migrations.CreateModel(
            name='Meniu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bauturi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.bauturi')),
                ('biscuiti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.biscuite')),
                ('inghetata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.inghetata')),
                ('prajituri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.prajituri')),
                ('torturi_inghetata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.torturi_inghetata')),
            ],
        ),
        migrations.AddField(
            model_name='magazine',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.sponsor'),
        ),
        migrations.AddField(
            model_name='inghetata',
            name='magazin',
            field=models.ManyToManyField(to='Gelaterie.magazine'),
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_achizitie', models.DateField(default=django.utils.timezone.now)),
                ('livrare_curier', models.BooleanField(default=True)),
                ('informatii', models.ManyToManyField(to='Gelaterie.informatii')),
            ],
        ),
        migrations.AddField(
            model_name='biscuite',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.informatii'),
        ),
        migrations.AddField(
            model_name='biscuite',
            name='magazin',
            field=models.ManyToManyField(to='Gelaterie.magazine'),
        ),
        migrations.AddField(
            model_name='bauturi',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.informatii'),
        ),
        migrations.AddField(
            model_name='bauturi',
            name='magazin',
            field=models.ManyToManyField(to='Gelaterie.magazine'),
        ),
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tara', models.CharField(max_length=50)),
                ('oras', models.CharField(max_length=50)),
                ('strada', models.CharField(max_length=150)),
                ('magazin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.magazine')),
            ],
        ),
    ]
