# Generated by Django 4.2.11 on 2024-11-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gelaterie', '0002_alter_biscuite_info_alter_prajituri_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='informatii',
            field=models.ManyToManyField(blank=True, to='Gelaterie.informatii'),
        ),
        migrations.AlterField(
            model_name='informatii',
            name='specificatii',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
