# Generated by Django 4.2.11 on 2024-11-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gelaterie', '0003_alter_comanda_informatii_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inghetata',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.informatii'),
        ),
    ]
