# Generated by Django 4.2.11 on 2024-12-02 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0003_customuser_email_confirmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField()),
                ('categorie', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizare', models.DateTimeField(default=django.utils.timezone.now)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gelaterie.informatii')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vizualizare',
            constraint=models.UniqueConstraint(fields=('utilizator', 'produs'), name='unique_vizualizare_per_utilizator'),
        ),
    ]
