# Generated by Django 4.2.11 on 2024-12-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0004_promotie_vizualizare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vizualizare',
            name='categorie',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
