# Generated by Django 4.2.11 on 2024-11-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gelaterie', '0004_alter_inghetata_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bauturi',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.informatii'),
        ),
        migrations.AlterField(
            model_name='biscuite',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.informatii'),
        ),
        migrations.AlterField(
            model_name='prajituri',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.informatii'),
        ),
        migrations.AlterField(
            model_name='torturi_inghetata',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gelaterie.informatii'),
        ),
    ]
