# Generated by Django 4.2.11 on 2024-12-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0005_vizualizare_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vizualizare',
            name='categorie',
        ),
    ]
