# Generated by Django 4.2.11 on 2024-11-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gelaterie', '0005_alter_bauturi_info_alter_biscuite_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bauturi',
            name='bautura',
            field=models.CharField(choices=[('CAFEA', 'cafea'), ('CEAI', 'ceai'), ('LAPTE', 'lapte'), ('MILKSHAKE', 'milkshake'), ('COCA-COLA', 'coca-cola'), ('PEPSI', 'pepsi'), ('FANTA', 'fanta'), ('LIPTON', 'lipton')], default='CAFEA'),
        ),
    ]
