# Generated by Django 4.2.11 on 2024-11-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gelaterie', '0008_alter_alergeni_nume_alergeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torturi_inghetata',
            name='nume_tort',
            field=models.CharField(choices=[('MOUSSE', 'mousse'), ('SACHER', 'sacher'), ('RED VELVET', 'red velvet'), ('BLACK FOREST', 'black forest')], default='MOUSSE'),
        ),
    ]
