# Generated by Django 4.2.11 on 2024-12-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0008_remove_vizualizare_unique_vizualizare_per_utilizator_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vizualizare',
            name='unique_vizualizare_per_utilizator',
        ),
        migrations.AddField(
            model_name='vizualizare',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vizualizare',
            name='produs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gelaterie.informatii'),
        ),
        migrations.AddConstraint(
            model_name='vizualizare',
            constraint=models.UniqueConstraint(fields=('utilizator', 'categorie'), name='unique_vizualizare_per_utilizator_categorie'),
        ),
    ]
