# Generated by Django 4.2.11 on 2024-12-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0009_remove_vizualizare_unique_vizualizare_per_utilizator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('vizualizeaza_oferta', 'Permite vizualizarea ofertei')]},
        ),
    ]
