# Generated by Django 4.2.11 on 2024-12-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0011_customuser_blocat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='blocat',
            new_name='is_blocked',
        ),
    ]
