# Generated by Django 4.2.11 on 2024-12-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0012_rename_blocat_customuser_is_blocked'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vizualizare',
            name='unique_vizualizare_per_utilizator_categorie',
        ),
    ]
