# Generated by Django 4.2.11 on 2024-12-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0014_vizualizare_unique_vizualizare_per_utilizator_categorie'),
    ]

    operations = [
    ]
