# Generated by Django 4.2.11 on 2024-12-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0015_auto_20241205_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
