# Generated by Django 4.2.11 on 2024-12-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0016_customuser_location_city_customuser_location_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location_country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location_region',
        ),
    ]
