# Generated by Django 4.2.11 on 2024-12-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelaterie', '0017_remove_customuser_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informatii',
            name='stoc',
            field=models.IntegerField(default=10),
        ),
    ]
